import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>

{/* <script async src="https://www.googletagmanager.com/gtag/js?id=G-XB2QZ2P7EQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XB2QZ2P7EQ');
</script> */}


{/* google adsen */}
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5234341717145583"
     crossorigin="anonymous"></script>


this for saad ads 

<script id="ad-script">
                {`
                    var atOptions = {
                        key: '0a8cce0ec638ad9a4f9feb94a0ff7e9e',
                        format: 'iframe',
                        height: 60,
                        width: 468,
                        params: {}
                    };
                `}
            </script>
            <script 
                src="//www.topcreativeformat.com/0a8cce0ec638ad9a4f9feb94a0ff7e9e/invoke.js"
                strategy="afterInteractive" // Load the script after the page is interactive
            />
{/* second saad ads */}
<script id="ad-script-2">
                {`
                    var atOptions = {
                        key: 'ae9a220771a53ca499d8bb485d1333aa',
                        format: 'iframe',
                        height: 90,
                        width: 728,
                        params: {}
                    };
                `}
            </script>
            <script 
                src="//www.topcreativeformat.com/ae9a220771a53ca499d8bb485d1333aa/invoke.js"
                strategy="afterInteractive"
            />

{/* this for google analytics */}


<script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-XB2QZ2P7EQ"
        />
        <script dangerouslySetInnerHTML={{ __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag() {
            window.dataLayer.push(arguments);
          }
          gtag('js', new Date());
          gtag('config', 'G-XB2QZ2P7EQ');
        `}} />




    </html>
  )
}
