import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
{/* <script async src="https://www.googletagmanager.com/gtag/js?id=G-XB2QZ2P7EQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XB2QZ2P7EQ');
</script> */}


{/* google adsen */}
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5234341717145583"
     crossorigin="anonymous"></script>

{/* google ads */}
<script
  async
  src="https://www.googletagmanager.com/gtag/js?id=AW-10789184238"
/>
<script
  dangerouslySetInnerHTML={{
    __html: `
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        window.dataLayer.push(arguments);
      }
      gtag('js', new Date());
      gtag('config', 'AW-10789184238');
    `,
  }}
/>


{/* this for google analytics */}


<script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-XB2QZ2P7EQ"
        />
        <script dangerouslySetInnerHTML={{ __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag() {
            window.dataLayer.push(arguments);
          }
          gtag('js', new Date());
          gtag('config', 'G-XB2QZ2P7EQ');
        `}} />




    </html>
  )
}
